[package]
name = "SGB"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.6"
sdl2 = "0.32.1"
pixels = "0.2.0"
winit  = "0.24.0"
winit_input_helper = "0.9.0"
